repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            files: "^backend/"
    - repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
          - id: isort
            files: "^backend/"
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.9
      hooks:
          - id: ruff-format
            args: ["--line-length", "150", "--preview"]
